#!/bin/sh

gtk-update-icon-cache -f -t -q /usr/share/icons/hicolor/

if [ -d "/usr/share/icons/ubuntu-mono-dark" ]; then
   gtk-update-icon-cache -f -t -q /usr/share/icons/ubuntu-mono-dark/
fi

if [ -d "/usr/share/icons/ubuntu-mono-light" ]; then
	gtk-update-icon-cache -f -t -q /usr/share/icons/ubuntu-mono-light/
fi

gtk-update-icon-cache -f -t -q /usr/share/icons/Yaru/
