#!/bin/sh

set -e

gtk-update-icon-cache -f -t -q /usr/share/icons/breeze/
gtk-update-icon-cache -f -t -q /usr/share/icons/hicolor/
gtk-update-icon-cache -f -t -q /usr/share/icons/Yaru/

if [ -d "/usr/share/icons/ubuntu-mono-light" ]; then
	gtk-update-icon-cache -f -t -q /usr/share/icons/ubuntu-mono-light/
fi

if [ -d "/usr/share/icons/ubuntu-mono-dark" ]; then
	gtk-update-icon-cache -f -t -q /usr/share/icons/ubuntu-mono-dark/
fi
